# Generated by Django 4.0.1 on 2022-01-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shusanket', '0002_auto_20220120_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-upload', '-created']},
        ),
    ]
